//
//  APICalls.swift
//  Stride
//
//  Created by Madhu Ramkumar on 5/31/23.
//

//import SpotifyiOS
import Foundation
import SwiftUI

struct RecommendationSeedObject: Codable, Hashable {
    var href: String
    var id: String
}

struct Song: Codable, Hashable {
    var seeds: [RecommendationSeedObject]
    var tracks: [TrackObject]
}

struct TrackObject: Codable, Hashable {
    var href: String
    var id: String
}

struct ArtistObject: Codable, Hashable {
    var href: String
    var id: String
}

struct UserTopArtists: Codable {
    var href: String
    var items: [ArtistObject]
}

struct UserTopTracks: Codable {
    var href: String
    var items: [TrackObject]
}

struct Genres: Codable {
    var genres: [String]
}

struct Recommendations: Codable {
    var tracks: [TrackObject]
}

struct UserInfo: Codable {
    var id: String
    
}

struct DeviceObject: Hashable, Codable {
    var id: String
    var is_active: Bool
    var is_restricted: Bool
    var type: String
}

struct Error: Codable {
    var status: Int
    var message: String
}

class APICalls: ObservableObject {
    var token = KeychainManager.standard.read(service: KeychainManager.standard.service, account: KeychainManager.standard.account, type: Auth.self)!.accessToken
    
    // updated in StartWorkoutView
    @Published var minBPM = ""
    @Published var maxBPM = ""
    @Published var workoutTime = ""
    
    // gathered from user data, generated by getTop endpoint
    @Published var seedArtists = ""
    @Published var seedTracks = ""
    @Published var seedGenres = ""
    @Published var recommendedTracks = ""
    @Published var userID = ""
    
    // playback info
    @Published var availableDevices: [DeviceObject]?
    
    func fetchAPI(_ endpoint: String, _ method: String) -> URLRequest {
        
        if (AuthorizationManager.authManager.isTokenExpired()) {
            AuthorizationManager.authManager.refreshAuthentication()
        }
        
        let url = URL(string: "https://api.spotify.com/v1/\(endpoint)")!
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        return request
    }
    
    func getAvailableDevices() {
        let request = fetchAPI("me/player/devices", "GET")
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
            
            // print out data for debugging purposes
            if let data = data {
                if let dataString = String(data: data, encoding: .utf8) {
                    print("got dataString: \n\(dataString)")
                }
            }

            guard let data = data, error == nil else {
                print("Error: \(error?.localizedDescription ?? "Unknown error")")
                return
            }
            
            
            if let response = response as? HTTPURLResponse {
                if (response.statusCode == 200) {
                    // assigns response JSON to UserTopArtists struct
                    guard let devices = try? JSONDecoder().decode([DeviceObject].self, from: data) else {
                        print("Error Decoding Device Details from JSON")
                        return
                    }
                    self.availableDevices = devices
                } else if (response.statusCode == 401) {
                    print("Access token expired")
                } else {
                    guard let errorInfo = try? JSONDecoder().decode(Error.self, from: data) else {
                        print("Error decoding error message details from JSON")
                        return
                    }
                    print (errorInfo.message)
                }
            }
        }
        task.resume()
    }
    
    // generates seed artists for getRecommendations endpoint based on users top artists
    func generateSeedArtists() {
        let request = fetchAPI("me/top/artists", "GET")
        let task = URLSession.shared.dataTask(with: request ) {data, response, error in
            
//            // print out data for debugging purposes
//            if let data = data {
//                if let dataString = String(data: data, encoding: .utf8) {
//                    print("got dataString: \n\(dataString)")
//                }
//            }

            guard let data = data, error == nil else {
                print("Error: \(error?.localizedDescription ?? "Unknown error")")
                return
            }
            
            if let response = response as? HTTPURLResponse {
                if (response.statusCode == 200) {
                    // assigns response JSON to UserTopArtists struct
                    guard let topArtists = try? JSONDecoder().decode(UserTopArtists.self, from: data) else {
                        print("Error Decoding Top Artist Details from JSON")
                        return
                    }
                    self.convertSeedArtistsToString(topArtists.items)
                } else if (response.statusCode == 401) {
                    print("Access token expired.")
                } else {
                    guard let errorInfo = try? JSONDecoder().decode(Error.self, from: data) else {
                        print("Error decoding error message details from JSON")
                        return
                    }
                    print (errorInfo.message)
                }
            }
        }
        task.resume()
    }
    
    
    // helper function to put JSON into a string
    func convertSeedArtistsToString(_ artists: [ArtistObject]) {
        for seed in artists {
            seedArtists += seed.id
        }
    }

    // generates seed tracks for getRecommendations endpoint based on users top tracks
    func generateSeedTracks() {
        let request = fetchAPI("me/top/tracks", "GET")
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
            
            // print out data for debugging purposes
            if let data = data {
                if let dataString = String(data: data, encoding: .utf8) {
                    print("got dataString: \n\(dataString)")
                }
            }
            
            guard let data = data, error == nil else {
                print("Error: \(error?.localizedDescription ?? "Unknown error")")
                return
            }
            
            if let response = response as? HTTPURLResponse {
                if (response.statusCode == 200) {
                    // assigns response JSON to UserTopArtists struct
                    guard let topTracks = try? JSONDecoder().decode(UserTopTracks.self, from: data) else {
                        print("Error Decoding Top Track Details from JSON")
                        return
                    }
                    self.convertSeedTracksToString(topTracks.items)
                    
                } else if (response.statusCode == 401) {
                    print("Access Token expired.")
                } else {
                    guard let errorInfo = try? JSONDecoder().decode(Error.self, from: data) else {
                        print("Error decoding error message details from JSON")
                        return
                    }
                    print (errorInfo.message)
                }
            }
        }
        task.resume()
    }
    
    // helper function to put JSON into a string
    func convertSeedTracksToString(_ tracks: [TrackObject]) {
        for seed in tracks {
            seedTracks += seed.id
        }
    }
    
    func generateSeedGenres() {
        let request = fetchAPI("recommendations/available-genre-seeds", "GET")
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
              
//            // print out data for debugging purposes
//            if let data = data {
//                if let dataString = String(data: data, encoding: .utf8) {
//                    print("got dataString: \n\(dataString)")
//                }
//            }
              
            guard let data = data, error == nil else {
                print("Error: \(error?.localizedDescription ?? "Unknown error")")
                return
            }
              
            if let response = response as? HTTPURLResponse {
                if (response.statusCode == 200) {
                      // assigns response JSON to UserTopArtists struct
                    guard let genreArray = try? JSONDecoder().decode(Genres.self, from: data) else {
                        print("Error Decoding Top Track Details from JSON")
                        return
                    }
                    self.convertSeedGenresToString(genreArray.genres)
                    
                } else if (response.statusCode == 401) {
                    print("Access token expired.")
                } else {
                    guard let errorInfo = try? JSONDecoder().decode(Error.self, from: data) else {
                        print("Error decoding error message details from JSON")
                        return
                    }
                    print (errorInfo.message)
                }
            }
        }
        task.resume()
    }
    
    // helper function to put JSON into a string
    func convertSeedGenresToString(_ genres: [String]) {
        for seed in genres {
            seedGenres += seed
        }
        
    }

    func getSongRecommendations() {
        
        // create URL for API request
        var urlComponents = URLComponents(string: "https://api.spotify.com/v1/recommendations")!
        urlComponents.queryItems = [// body
            URLQueryItem(name: "seed_artists", value: seedArtists),
            URLQueryItem(name: "seed_genres", value: seedGenres),
            URLQueryItem(name: "seed_tracks", value: seedTracks),
            URLQueryItem(name: "min_tempo", value: minBPM),
            URLQueryItem(name: "max_tempo", value: maxBPM)
        ]
        guard let url = urlComponents.url else {
            fatalError("Missing URL!")
        }
        
        // create API Request
        var request = URLRequest(url: url)
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
              
            // print out data for debugging purposes
            if let data = data {
                if let dataString = String(data: data, encoding: .utf8) {
                    print("got dataString: \n\(dataString)")
                }
            }
              
            guard let data = data, error == nil else {
                print("Error: \(error?.localizedDescription ?? "Unknown error")")
                return
            }
              
            if let response = response as? HTTPURLResponse {
                if (response.statusCode == 200) {
                      // assigns response JSON to UserTopArtists struct
                    guard let recommendations = try? JSONDecoder().decode(Recommendations.self, from: data) else {
                        print("Error Decoding Recommendation Details from JSON")
                        return
                    }
                    self.convertRecommendedTracksToString(recommendations.tracks)
                    
                } else if (response.statusCode == 401) {
                    print("Access token expired")
                } else {
                    guard let errorInfo = try? JSONDecoder().decode(Error.self, from: data) else {
                        print("Error decoding error message details from JSON")
                        return
                    }
                    print (errorInfo.message)
                }
            }
        }
        task.resume()
    }
    
    func convertRecommendedTracksToString(_ recTracks: [TrackObject]) {
        for seed in recTracks {
            recommendedTracks += seed.id
        }
    }
    
    func getUserID() {
        let request = fetchAPI("me", "GET")
        let task = URLSession.shared.dataTask(with: request) {data, response, error in

            // print out data for debugging purposes
            if let data = data {
                if let dataString = String(data: data, encoding: .utf8) {
                    print("got dataString: \n\(dataString)")
                }
            }

            guard let data = data, error == nil else {
                print("Error: \(error?.localizedDescription ?? "Unknown error")")
                return
            }

            if let response = response as? HTTPURLResponse {
                if (response.statusCode == 200) {
                      // assigns response JSON to UserTopArtists struct
                    guard let user = try? JSONDecoder().decode(UserInfo.self, from: data) else {
                        print("Error Decoding Top Track Details from JSON")
                        return
                    }
                    self.userID = user.id

                } else if (response.statusCode == 401) {
                    print("Access token expired.")
                } else {
                    guard let errorInfo = try? JSONDecoder().decode(Error.self, from: data) else {
                        print("Error decoding error message details from JSON")
                        return
                    }
                    print (errorInfo.message)
                }
            }
        }
        task.resume()
    }
    
    // PLAYBACK FUNCTIONS
    func startPlayback() {
        var urlComponents = URLComponents(string: "https://api.spotify.com/v1/me/player/play")!
        urlComponents.queryItems = [// body
            URLQueryItem(name: "device_id", value: "155444755d6ec1e3fa30c669da878ef5046d4fb1"),
        ] // have to supply the iphone device id, otherwise it wont play
        guard let url = urlComponents.url else {
            fatalError("Missing URL!")
        }
        
        // create API Request
        var request = URLRequest(url: url)
        request.httpMethod = "PUT"
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        request.addValue("application/json", forHTTPHeaderField: "Content-Type")
        let body: [String: Any] = ["uris": ["spotify:track:5VA4Ispp52EA1sOqzMz3Av"], "position_ms": 0] // change this to recommended URIS
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
            print("playback started")
        }
        task.resume()
    }
    
    // when workout ended automatically or by user, end playlist
    func pausePlayback() {
        var urlComponents = URLComponents(string: "https://api.spotify.com/v1/me/player/pause")!
        urlComponents.queryItems = [// body
            URLQueryItem(name: "device_id", value: "155444755d6ec1e3fa30c669da878ef5046d4fb1"),
        ] // have to supply the iphone device id, otherwise it wont play
        guard let url = urlComponents.url else {
            fatalError("Missing URL!")
        }
        
        // create API Request
        var request = URLRequest(url: url)
        request.httpMethod = "PUT"
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
            print("playback paused")
        }
        task.resume()
    }

    func skipToPrevious() {
        var urlComponents = URLComponents(string: "https://api.spotify.com/v1/me/player/previous")!
        urlComponents.queryItems = [// body
            URLQueryItem(name: "device_id", value: "155444755d6ec1e3fa30c669da878ef5046d4fb1"),
        ] // have to supply the iphone device id, otherwise it wont play
        guard let url = urlComponents.url else {
            fatalError("Missing URL!")
        }
        
        // create API Request
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
            print("skip to previous")
        }
        task.resume()
    }
    
    func skipToNext() {
        var urlComponents = URLComponents(string: "https://api.spotify.com/v1/me/player/next")!
        urlComponents.queryItems = [// body
            URLQueryItem(name: "device_id", value: "155444755d6ec1e3fa30c669da878ef5046d4fb1"),
        ] // have to supply the iphone device id, otherwise it wont play
        guard let url = urlComponents.url else {
            fatalError("Missing URL!")
        }
        
        // create API Request
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        let task = URLSession.shared.dataTask(with: request) {data, response, error in
            print("skip to next")
        }
        task.resume()
    }
    
    // can be used to make progress bar / scrubber
    func getPlaybackState() {
        
    }

    // create playlist of recommended songs whose length = specified workout time
    func createPlaylist() {



    }
    
    // invoked if user agrees to save playlist to libary after workout finishes
    func savePlaylistToLibrary() {
        
    }
    
    
}
